version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - PORT=8080

networks:
  app_network:
    driver: bridge