version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - app_network
      
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
             
networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: